### PR TITLE
use a better kind of apple

### PR DESCRIPTION
**Pull request by cccCody**

### CODE REVIEW

**Comment by cccCody** [comment]
💋

**Comment by scrudgey** [comment]
thanks for suggesting a apple

**Review by gopperman — COMMENTED** [review]
The Honeycrisp, in addition to not being a garbage apple, is more accessible for colorblind users, who may not be able to detect red

**Comment by gopperman** [comment]
:shipit:

**Comment by waltz** [comment]
lgtm

**Pull request merged**
